# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62df419d59c7d0046d3dc003155322690ebe8bb9d26d1ca029bdef84fbd299fdb20b14f5f0ec3c3458bc07240fd2b3b714ffe68bbe008384a95bdebcb05487b4

test:
  secret_key_base: f61f2a09cb44b383f2987d1533c4de45f5777fd13b8cce7257ade40f811e276b4138d0577f3e2aa83e062b1538bf270bfe6fbf85f9de41380eea44fd3c67bc1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
